DROP DATABASE IF EXISTS INSUMOS;
CREATE DATABASE INSUMOS;
USE INSUMOS;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE CENTRO(
	ID INT AUTO_INCREMENT,
    PRIMARY KEY(ID),
    NOMBRE VARCHAR(100) NOT NULL
);

CREATE TABLE INSUMO(
	ID INT AUTO_INCREMENT,
    PRIMARY KEY(ID),
	NOMBRE VARCHAR(50) NOT NULL,
    DIMENSIONES VARCHAR(30),
    COLOR VARCHAR(30),
    TIPO SET('BOLSAS','LIQUIDOS','CAFETERIA','HERRAMIENTAS','INSUMOS_GENERALES','EPP','TOALLAS','OTROS') NOT NULL
);

CREATE TABLE USUARIOS(
	ID INT AUTO_INCREMENT,
    PRIMARY KEY(ID),    
	CONTRASENA VARCHAR(50) NOT NULL,
    ID_CENTRO INT NOT NULL,
    FOREIGN KEY (ID_CENTRO) REFERENCES CENTRO(ID)
);
	CREATE TABLE TRANSACCION(
	ID INT AUTO_INCREMENT,
    PRIMARY KEY(ID),
	TIPO SET('ENTRADA','SALIDA'),
    CANTIDAD INT NOT NULL,
    JUSTIFICACION TINYTEXT,
    SERVICIO VARCHAR(60),
    PERSONA VARCHAR(60),
	FECHA DATETIME,
    ID_CENTRO INT NOT NULL,
    FOREIGN KEY (ID_CENTRO) REFERENCES CENTRO(ID),
    ID_INSUMO INT NOT NULL,
    FOREIGN KEY (ID_INSUMO) REFERENCES INSUMO(ID)
);

CREATE TABLE INVENTARIO(
	ID INT AUTO_INCREMENT,
    PRIMARY KEY(ID),
    ID_INSUMO INT NOT NULL,
    FOREIGN KEY(ID_INSUMO) REFERENCES INSUMO(ID),
    ID_CENTRO INT NOT NULL,
    FOREIGN KEY(ID_CENTRO) REFERENCES CENTRO(ID),
    CANTIDAD INT NOT NULL DEFAULT 0
);

-- INSERT DE CENTROS
INSERT INTO CENTRO(NOMBRE) VALUES ('HOSPITAL DE KENNEDY'); 

-- INSERT DE INSUMOS
INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 20X20','20X20','ROJO','BOLSAS');
INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 20X20','20X20','AZUL','BOLSAS');
INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 20X20','20X20','AMARILLO','BOLSAS');

INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 50X50','50X50','ROJO','BOLSAS');
INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 50X50','50X50','AZUL','BOLSAS');
INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 50X50','50X50','AMARILLO','BOLSAS');

INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 100X100','100X100','ROJO','BOLSAS');
INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 100X100','100X100','AZUL','BOLSAS');
INSERT INTO INSUMO(NOMBRE,DIMENSIONES,COLOR,TIPO) VALUES ('BOLSA 100X100','100X100','AMARILLO','BOLSAS');

INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('TOALLA 1','TOALLAS');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('TOALLA 2','TOALLAS');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('PAPEL 3','TOALLAS');

INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('HIPOCLORITO','LIQUIDOS');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('JABON','LIQUIDOS');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('CLOROX','LIQUIDOS');

INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('TINTO 20GR','CAFETERIA');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('AROMÁTICA','CAFETERIA');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('PAN','CAFETERIA');

INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('ESCOBA','HERRAMIENTAS');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('TRAPERO','HERRAMIENTAS');

INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('JABON EN POLVO','INSUMOS_GENERALES');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('LAVALOZA','INSUMOS_GENERALES');

INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('GAFAS','EPP');
INSERT INTO INSUMO(NOMBRE,TIPO) VALUES ('TRAJE','EPP');

SELECT * FROM transaccion;
SELECT * FROM VISTA_INSUMOS;
-- INSERT DE INVENTARIO
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(1,1,40); 
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(2,1,20); 
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(3,1,30); 
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(4,1,67);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(10,1,40);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(11,1,2);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(12,1,0);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(13,1,29);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(14,1,22);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(15,1,1);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(16,1,100);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(17,1,200);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(18,1,30);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(19,1,33);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(20,1,15);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(21,1,19);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(22,1,10);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(23,1,20);
INSERT INTO INVENTARIO(ID_INSUMO,ID_CENTRO,CANTIDAD) VALUES(24,1,23);
-- VISTAS
CREATE OR REPLACE VIEW VISTA_INSUMOS AS
SELECT INSUMO_INVENTARIO.*,CENTRO.NOMBRE AS 'NOMBRE_CENTRO' FROM (SELECT INSUMO.*, INVENTARIO.ID_CENTRO, INVENTARIO.CANTIDAD FROM INSUMO INNER JOIN INVENTARIO ON INSUMO.ID = INVENTARIO.ID_INSUMO) AS INSUMO_INVENTARIO INNER JOIN CENTRO ON CENTRO.ID = INSUMO_INVENTARIO.ID_CENTRO;
SELECT * FROM VISTA_INSUMOS;

CREATE OR REPLACE VIEW VISTA_TRANSACCION AS
SELECT SUBCONSULTA.*, CENTRO.NOMBRE FROM (SELECT TRANSACCION.*,INSUMO.NOMBRE AS "NOMBRE_INSUMO",INSUMO.COLOR,INSUMO.TIPO AS "TIPO_INSUMO" FROM TRANSACCION INNER JOIN INSUMO WHERE TRANSACCION.ID_INSUMO = INSUMO.ID) AS SUBCONSULTA INNER JOIN CENTRO ON SUBCONSULTA.ID_CENTRO = CENTRO.ID;
SELECT * FROM VISTA_TRANSACCION;

-- PROCEDIMIENTOS
DELIMITER //
CREATE PROCEDURE MODIFICAR_CANTIDAD(
	IDINSUMO INT, CAMBIO INT
)
BEGIN
	UPDATE INVENTARIO SET CANTIDAD = CANTIDAD + CAMBIO WHERE ID_INSUMO = IDINSUMO;
END // 
DELIMITER ;

CALL MODIFICAR_CANTIDAD(1,7);
select * from insumo;
select * from inventario;
